### ISSUE TITLE
Please fix CI and publish latest SDK

### ISSUE THREAD

**Issue by polyomino24** [criteo/criteo-api-java-sdk#16]
It seems that CI failed when publishing SDK to MavenCentral.

https://github.com/criteo/criteo-api-java-sdk/actions/runs/9561993712/job/26357421206

**Comment by tibonihoo** [comment]
Hello !
Sorry for this late reply, and thanks for reporting.

We've been looking into this, and the process to "fix" that authorization issue is taking longer that we' expected but we're still on it.

**Comment by ttembou** [comment]
Hello !

Sorry for the delay,
We've fixed the blocker on our side for the publication of the SDK in Maven, latest updates are now available !

**Comment by polyomino24** [comment]
Thanks!
